name: airatlas_analytics
version: '0.1.0'
config-version: 2
profile: airatlas_analytics
require-dbt-version: [">=1.12.0", "<1.13.0"]

model-paths: ["models"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages", "logs"]

models:
  airatlas_analytics:
    +materialized: view
    staging:
      +schema: staging
    intermediate:
      +schema: intermediate
